FROM python:3.9.10-slim
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
RUN apt-get update && apt-get upgrade -y
RUN pip install poetry
RUN apt update && apt install supervisor -y
WORKDIR /app
COPY  pyproject.toml /app/
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction
#COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY . /app
CMD ["celery", "-A", "app.tasks.celery", "worker", "--loglevel=info"]
