version: "3.8"
services:
  web:
    build: .
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    container_name: postgresql_db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB

  redis:
    image: redis
    restart: always

  celery:
    build:
      context: ./celery
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./celery:/app
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      - celery
