from tortoise.timezone import now

start = now()
wordlist = ["qwe", "qew", "sad", "word", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa","qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa","qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa","qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa","qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",
            "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe",
            "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew",
            "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad",
            "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx",
            "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad",
            "dsadsa", "qwe", "qew", "sad", "cxzx", "sadsad", "dsadsa",]


newlist = map(str.upper, wordlist)
print(type(newlist))

# newlist = []
# for word in wordlist:
#     newlist.append(word.upper())
# newlist = map(str.upper, wordlist)

end = now()

duration = end - start

print("start: ", start, " end: ", end, " duration: ", duration)
