"""create new model to link tasks with mapper

Revision ID: 1412dd8fd8c0
Revises: 338dd7156028
Create Date: 2023-03-19 18:28:02.335711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1412dd8fd8c0'
down_revision = '338dd7156028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappertask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('received', 'revoked', 'success', 'failed', name='celerytaskstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mappertask_company_id'), 'mappertask', ['company_id'], unique=False)
    op.create_index(op.f('ix_mappertask_id'), 'mappertask', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mappertask_id'), table_name='mappertask')
    op.drop_index(op.f('ix_mappertask_company_id'), table_name='mappertask')
    op.drop_table('mappertask')
    # ### end Alembic commands ###
