"""add set_active_at to mapper config

Revision ID: 6601c18f9d00
Revises: d57d5cccd59d
Create Date: 2023-03-13 13:14:40.477747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6601c18f9d00'
down_revision = 'd57d5cccd59d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processconfig', sa.Column('set_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processconfig', 'set_active_at')
    # ### end Alembic commands ###
