"""add description and is_active to process config

Revision ID: d57d5cccd59d
Revises: 0a817bb81ca9
Create Date: 2023-03-12 16:13:17.618723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57d5cccd59d'
down_revision = '0a817bb81ca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processconfig', sa.Column('description', sa.String(), nullable=True))
    op.add_column('processconfig', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processconfig', 'is_active')
    op.drop_column('processconfig', 'description')
    # ### end Alembic commands ###
