"""add error message to row failed history

Revision ID: da64197c67bd
Revises: ead973612d02
Create Date: 2023-04-19 11:40:23.767699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da64197c67bd'
down_revision = 'ead973612d02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filehistoryfailedrows', sa.Column('error_msg', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filehistoryfailedrows', 'error_msg')
    # ### end Alembic commands ###
