"""modify failure rows

Revision ID: ead973612d02
Revises: 10d7e53d304e
Create Date: 2023-04-16 11:10:31.618397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead973612d02'
down_revision = '10d7e53d304e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filehistoryfailedrows', sa.Column('is_success', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filehistoryfailedrows', 'is_success')
    # ### end Alembic commands ###
