"""modify history

Revision ID: eae592990f33
Revises: 98ba98eeaceb
Create Date: 2023-04-05 23:30:59.579649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae592990f33'
down_revision = '98ba98eeaceb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE TYPE status AS ENUM ('pending', 'in_progress', 'success', 'failed')")

    op.add_column('filereceivehistory', sa.Column('total_rows', sa.Integer(), nullable=True))
    op.add_column('filereceivehistory', sa.Column('total_success', sa.Integer(), nullable=True))
    op.add_column('filereceivehistory', sa.Column('total_failure', sa.Integer(), nullable=True))
    op.add_column('filereceivehistory', sa.Column('history_status', sa.Enum('pending', 'in_progress', 'success', 'failed', name='status'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filereceivehistory', 'history_status')
    op.drop_column('filereceivehistory', 'total_failure')
    op.drop_column('filereceivehistory', 'total_success')
    op.drop_column('filereceivehistory', 'total_rows')
    op.drop_column('filereceivehistory', 'history_status')
    op.execute("DROP TYPE historystatus;")
    # ### end Alembic commands ###
